export const basicInfoActionType = {
  SUBMITING_BASICINFO_START: "SUBMITING_BASICINFO_START",
  SUBMITING_BASICINFO_SUCCESS: "SUBMITING_BASICINFO_SUCCESS",
  SUBMITING_BASICINFO_ERROR: "SUBMITING_BASICINFO_ERROR",
  GET_BASICINFO_START: "GET_BASICINFO_START",
  GET_BASICINFO_SUCCESS: "GET_BASICINFO_SUCCESS",
  GET_BASICINFO_ERROR: "GET_BASICINFO_ERROR",
};
