export const workexperinceActionType = {
  SUBMIT_WORKEXP_START: "SUBMITING_WORKEXP_START",
  SUBMIT_WORKEXP_SUCCESS: "SUBMIT_WORKEXP_SUCCESS",
  SUBMIT_WORKEXP_ERROR: "SUBMIT_WORKEXP_ERROR",
  DELETE_WORKEXP_START: "DELETE_WORKEXP_START",
  DELETE_WORKEXP_SUCCESS: "DELETE_WORKEXP_SUCCESS",
  DELETE_WORKEXP_ERROR: "DELETE_WORKEXP_ERROR",
  GET_WORKEXPERINCE_START: "GET_WORKEXPERINCE_START",
  GET_WORKEXPERINCE_SUCCESS: "GET_WORKEXPERINCE_SUCCESS",
  GET_WORKEXPERINCE_ERROR: "GET_WORKEXPERINCE_ERROR",
};
