export const workexperinceActionType = {
  GET_WORKEXPERINCE_START: "GET_WORKEXPERINCE_START",
  GET_WORKEXPERINCE_SUCCESS: "GET_WORKEXPERINCE_SUCCESS",
  GET_WORKEXPERINCE_ERROR: "GET_WORKEXPERINCE_ERROR",
};
