export const oldcvActionType = {
  GET_OLDCV_START: "GET_OLDCV_START",
  GET_OLDCV_SUCCESS: "GET_OLDCV_SUCCESS",
  GET_OLDCV_ERROR: "GET_OLDCV_ERROR",
  DELETE_CV_START: "DELETE_CV_START",
  DELETE_CV_SUCCESS: "DELETE_CV_SUCCESS",
  DELETE_CV_ERROR: "DELETE_CV_ERROR",
};
