export const createnewcvTypeAction = {
  GETNAMEOFCV_START: "GETNAMEOFCV_START",
  GETNAMEOFCV_SUCCESS: "GETNAMEOFCV_SUCCESS",
  GETNAMEOFCV_ERROR: "GETNAMEOFCV_ERROR",
  CHANGENAMECV_START: "CHANGENAMECV_START",
  CHANGENAMECV_SUCCESS: "CHANGENAMECV_SUCCESS",
  CHANGENAMECV_ERROR: "CHANGENAMECV_ERROR",
};
