export const createnewcvTypeAction = {
  CREATENEWCV_START: "CREATENEWCV_START",
  CREATENEWCV_SUCCESS: "CREATENEWCV_SUCCESS",
  CREATENEWCV_ERROR: "CREATENEWCV_ERROR",
  GETNAMEOFCV_START: "GETNAMEOFCV_START",
  GETNAMEOFCV_SUCCESS: "GETNAMEOFCV_SUCCESS",
  GETNAMEOFCV_ERROR: "GETNAMEOFCV_ERROR",
  CHANGENAMECV_START: "CHANGENAMECV_START",
  CHANGENAMECV_SUCCESS: "CHANGENAMECV_SUCCESS",
  CHANGENAMECV_ERROR: "CHANGENAMECV_ERROR",
};
