export const newCkEdtiorTypeAction = {
  SUBMITING_CKEDITOR_START: "SUBMITING_CKEDITOR_START",
  SUBMITING_CKEDITOR_SUCCESS: "SUBMITING_CKEDITOR_SUCCESS",
  SUBMITING_CKEDITOR_ERROR: "SUBMITING_CKEDITOR_ERROR",
  GET_OLD_CKEDIOTR_DATA_START: "GET_OLD_CKEDIOTR_DATA_START",
  GET_OLD_CKEDIOTR_DATA_SUCCESS: "GET_OLD_CKEDIOTR_DATA_SUCCESS",
  GET_OLD_CKEDIOTR_DATA_ERROR: "GET_OLD_CKEDIOTR_DATA_ERROR",
};
