export const newCkEdtiorTypeAction = {
  GET_OLD_CKEDIOTR_DATA_START: "GET_OLD_CKEDIOTR_DATA_START",
  GET_OLD_CKEDIOTR_DATA_SUCCESS: "GET_OLD_CKEDIOTR_DATA_SUCCESS",
  GET_OLD_CKEDIOTR_DATA_ERROR: "GET_OLD_CKEDIOTR_DATA_ERROR",
};
