export const educationActionType = {
  SUBMITING_EDUCATION_START: "SUBMITING_EDUCATION_START",
  SUBMITING_EDUCATION_SUCCESS: "SUBMITING_EDUCATION_SUCCESS",
  SUBMITING_EDUCATION_ERROR: "SUBMITING_EDUCATION_ERROR",
  GET_EDUCATION_START: "GET_EDUCATION_START",
  GET_EDUCATION_SUCCESS: "GET_EDUCATION_SUCCESS",
  GET_EDUCATION_ERROR: "GET_EDUCATION_ERROR",
};
