export const qualificationsActionType = {
  GET_QUALIFICATIONS_START: "GET_QUALIFICATIONS_START",
  GET_QUALIFICATIONS_SUCCESS: "GET_QUALIFICATIONS_SUCCESS",
  GET_QUALIFICATIONS_ERROR: "GET_QUALIFICATIONS_ERROR",
};
