export const workexpernceActionType = {
  GET_WORKEXPERNCE_START: "GET_WORKEXPERNCE_START",
  GET_WORKEXPERNCE_SUCCESS: "GET_WORKEXPERNCE_SUCCESS",
  GET_WORKEXPERNCE_ERROR: "GET_WORKEXPERNCE_ERROR",
};
